global:
  scrape_interval: 15s # Chu kỳ lấy dữ liệu (15 giây 1 lần)

scrape_configs:
  - job_name: 'nestjs-app'
    metrics_path: /api/v1/metrics # Đường dẫn API trong codebase thực tế
    static_configs:
      # host.docker.internal giúp container Prometheus nhìn thấy ứng dụng chạy trên máy host
      - targets: ['host.docker.internal:3300', 'host.docker.internal:3001']
